package org.finos.fdc3.schema;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Jackson Mix-ins for FDC3 schema types to handle optional fields.
 * 
 * Generated by scripts/generate-mixins.js - regenerate after schema changes.
 * 
 * In JSON Schema, optional fields (not in "required" array) that don't allow null
 * should be omitted when null, not serialized as "field": null.
 * These mix-ins apply @JsonInclude(NON_NULL) to those fields.
 */
public final class NullHandlingMixin {
    
    private NullHandlingMixin() {
        // Utility class
    }
    
    /**
     * Register all mix-ins with the given ObjectMapper.
     */
    public static void registerAll(ObjectMapper om) {
        om.addMixIn(AppIdentifier.class, AppIdentifierMixin.class);
        om.addMixIn(AppMetadata.class, AppMetadataMixin.class);
        om.addMixIn(ImplementationMetadata.class, ImplementationMetadataMixin.class);
        om.addMixIn(BroadcastEventPayload.class, BroadcastEventPayloadMixin.class);
        om.addMixIn(Channel.class, ChannelMixin.class);
        om.addMixIn(DisplayMetadata.class, DisplayMetadataMixin.class);
        om.addMixIn(FindIntentRequestPayload.class, FindIntentRequestPayloadMixin.class);
        om.addMixIn(FindIntentsByContextRequestPayload.class, FindIntentsByContextRequestPayloadMixin.class);
        om.addMixIn(Icon.class, IconMixin.class);
        om.addMixIn(Image.class, ImageMixin.class);
        om.addMixIn(IntentEventPayload.class, IntentEventPayloadMixin.class);
        om.addMixIn(IntentMetadata.class, IntentMetadataMixin.class);
        om.addMixIn(OpenRequestPayload.class, OpenRequestPayloadMixin.class);
        om.addMixIn(RaiseIntentForContextRequestPayload.class, RaiseIntentForContextRequestPayloadMixin.class);
        om.addMixIn(RaiseIntentRequestPayload.class, RaiseIntentRequestPayloadMixin.class);
    }
    
    // === Mix-in classes for each schema type ===
    
    public static abstract class AppIdentifierMixin {
        @JsonProperty("instanceId")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getInstanceId();

        @JsonProperty("desktopAgent")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getDesktopAgent();
    }
    
    public static abstract class AppMetadataMixin {
        @JsonProperty("name")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getName();

        @JsonProperty("version")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getVersion();

        @JsonProperty("title")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getTitle();

        @JsonProperty("tooltip")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getTooltip();

        @JsonProperty("description")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getDescription();

        @JsonProperty("icons")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getIcons();

        @JsonProperty("screenshots")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getScreenshots();

        @JsonProperty("resultType")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getResultType();

        @JsonProperty("instanceId")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getInstanceId();

        @JsonProperty("instanceMetadata")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getInstanceMetadata();

        @JsonProperty("desktopAgent")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getDesktopAgent();
    }
    
    public static abstract class ImplementationMetadataMixin {
        @JsonProperty("optionalFeatures")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getOptionalFeatures();

        @JsonProperty("providerVersion")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getProviderVersion();
    }
    
    public static abstract class BroadcastEventPayloadMixin {
        @JsonProperty("originatingApp")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getOriginatingApp();
    }
    
    public static abstract class ChannelMixin {
        @JsonProperty("displayMetadata")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getDisplayMetadata();
    }
    
    public static abstract class DisplayMetadataMixin {
        @JsonProperty("name")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getName();

        @JsonProperty("color")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getColor();

        @JsonProperty("glyph")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getGlyph();
    }
    
    public static abstract class FindIntentRequestPayloadMixin {
        @JsonProperty("context")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getContext();

        @JsonProperty("resultType")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getResultType();
    }
    
    public static abstract class FindIntentsByContextRequestPayloadMixin {
        @JsonProperty("resultType")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getResultType();
    }
    
    public static abstract class IconMixin {
        @JsonProperty("size")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getSize();

        @JsonProperty("type")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getType();
    }
    
    public static abstract class ImageMixin {
        @JsonProperty("size")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getSize();

        @JsonProperty("type")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getType();

        @JsonProperty("label")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getLabel();
    }
    
    public static abstract class IntentEventPayloadMixin {
        @JsonProperty("originatingApp")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getOriginatingApp();
    }
    
    public static abstract class IntentMetadataMixin {
        @JsonProperty("displayName")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getDisplayName();
    }
    
    public static abstract class OpenRequestPayloadMixin {
        @JsonProperty("context")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getContext();
    }
    
    public static abstract class RaiseIntentForContextRequestPayloadMixin {
        @JsonProperty("app")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getApp();
    }
    
    public static abstract class RaiseIntentRequestPayloadMixin {
        @JsonProperty("app")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getApp();
    }
}

