package org.finos.fdc3.schema;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * Jackson Mix-ins for FDC3 schema types to handle optional fields.
 * 
 * Generated by scripts/generate-mixins.js - regenerate after schema changes.
 * 
 * In JSON Schema, optional fields (not in "required" array) that don't allow null
 * should be omitted when null, not serialized as "field": null.
 * These mix-ins apply @JsonInclude(NON_NULL) to those fields.
 * 
 * Note: Some types (AppIdentifier, AppMetadata, DisplayMetadata, Icon, Image, 
 * ImplementationMetadata, IntentMetadata) are now beans in fdc3-standard with 
 * @JsonInclude(NON_NULL) at class level, so they don't need mixins here.
 */
public final class NullHandlingMixin {
    
    private NullHandlingMixin() {
        // Utility class
    }
    
    /**
     * Register all mix-ins with the given ObjectMapper.
     * Note: Types from fdc3-standard (AppIdentifier, AppMetadata, DisplayMetadata, 
     * Icon, Image, ImplementationMetadata, IntentMetadata) already have proper 
     * JSON annotations and don't need mixins.
     */
    public static void registerAll(ObjectMapper om) {
        om.addMixIn(BroadcastEventPayload.class, BroadcastEventPayloadMixin.class);
        om.addMixIn(Channel.class, ChannelMixin.class);
        om.addMixIn(FindIntentRequestPayload.class, FindIntentRequestPayloadMixin.class);
        om.addMixIn(FindIntentsByContextRequestPayload.class, FindIntentsByContextRequestPayloadMixin.class);
        om.addMixIn(IntentEventPayload.class, IntentEventPayloadMixin.class);
        om.addMixIn(OpenRequestPayload.class, OpenRequestPayloadMixin.class);
        om.addMixIn(RaiseIntentForContextRequestPayload.class, RaiseIntentForContextRequestPayloadMixin.class);
        om.addMixIn(RaiseIntentRequestPayload.class, RaiseIntentRequestPayloadMixin.class);
    }
    
    // === Mix-in classes for schema types that need null handling ===
    
    public static abstract class BroadcastEventPayloadMixin {
        @JsonProperty("originatingApp")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getOriginatingApp();
    }
    
    public static abstract class ChannelMixin {
        @JsonProperty("displayMetadata")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getDisplayMetadata();
    }
    
    public static abstract class FindIntentRequestPayloadMixin {
        @JsonProperty("context")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getContext();

        @JsonProperty("resultType")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getResultType();
    }
    
    public static abstract class FindIntentsByContextRequestPayloadMixin {
        @JsonProperty("resultType")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract String getResultType();
    }
    
    public static abstract class IntentEventPayloadMixin {
        @JsonProperty("originatingApp")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getOriginatingApp();
    }
    
    public static abstract class OpenRequestPayloadMixin {
        @JsonProperty("context")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getContext();
    }
    
    public static abstract class RaiseIntentForContextRequestPayloadMixin {
        @JsonProperty("app")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getApp();
    }
    
    public static abstract class RaiseIntentRequestPayloadMixin {
        @JsonProperty("app")
        @JsonInclude(JsonInclude.Include.NON_NULL)
        abstract Object getApp();
    }
}
